<?php
/** @var \Lib3rdParty\Authentication\AuthenticatedUserWithForcePasswordResetInterface $user **/
echo '<h1>'.$user->getName().' | Reset Password</h1>';
echo '<form method="post">
<p class="row"><label class="col-lg-2 col-md-2" for="pass">Password: </label><span class="col-lg-4 col-md-4"><input type="password" name="oPass" id="pass" class="col-lg-12 col-md-12" /></span></p>
<p class="row"><label class="col-lg-2 col-md-2" for="npass">New Password: </label><span class="col-lg-4 col-md-4"><input type="password" name="nPass" id="npass" class="col-lg-12 col-md-12" /></p>
<p class="row"><label class="col-lg-2 col-md-2" for="cpass">Confirm Password: </label><span class="col-lg-4 col-md-4"><input type="password" name="cPass" id="cpass" class="col-lg-12 col-md-12" /></span></p>
<p class="row"><label class="col-lg-2 col-md-2">&nbsp;</label><span class="col-lg-2 col-md-2"><button class="col-lg-12 col-md-12 btn btn-default btn-info">Change</button></span><span class="col-lg-4 col-md-4"><a href="'.$this->url('login').'" class="btn btn-default">Cancel</a></span></p>
</form>';

