<?php
$prdCode = 'Account Login';
$this->headTitle($prdCode);

#if(!empty($error)) echo '<pre>'.$error.'</pre>';
#if($isFormSubmitted && !$isPasswordOK) echo '<h3>Incorrect login information</h3>';
/*
 $form = $this->form;
 $form->setAttribute('action', $this->url('login'));
 $form->prepare();
 echo $this->form()->openTag($form);
 #echo '<div class="form-group">'.$this->formRow($form->get('loginId')).'</div>';
 #echo '<div class="form-group">'.$this->formRow($form->get('loginPass')).'</div>';
 echo $this->formCollection($form);
 #echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();
*/

#echo '<h3>whoAmI: '.$this->whoAmI.'</h3>';

/*

*/

$this->headLink()->offsetSetStylesheet(101, $this->basePath().'/css/login.css');

$loginForm=$this->plugin('loginForm');

?>

<div class="wms-form-control accountlogingeneral">

	<div class="creant-new-account">
		<span class="creant-new-account-title"><?php echo $prdCode; ?></span> <span
			class="login-account-icon"></span>
	</div>
	<?php echo (!empty($error)?'<div class="required-field-error-message">'.$error.'</div>':''); ?>
	<div class="welcome-info">
		<span class="rtcustomer">RETURNING CUSTOMER</span><br> <span
			class="welcome-message"> Welcome Back! Please enter your email
			address and password below. </span>

	</div>

	<div class="custom-table account-login">

		<div class="tr">
			<div class="heading2 td">
			<!-- login form --> <?=$loginForm()?> <?=(true==$anonymousLoginEnabled?'<a href="'.$this->url('login', array('action'=>'anonymous-login')).'">Proceed as Guest</a> '.(isset($forgotPasswordUrl)?'| ':''):'')?>
					<?php echo (isset($forgotPasswordUrl)?'<font><a class="underlinetext" href="'.$forgotPasswordUrl.'">Forgot your password?</a></font>':''); ?>
					<?php if(isset($registrationUrl)): ?><?php echo (true==$anonymousLoginEnabled?'<br /><br /><span class="underlinetext">Or, click here to</span><br />':(isset($forgotPasswordUrl)?' | ':'')); ?><a href="<?php echo $registrationUrl;?>" class="underlinetext"><b>CREATE NEW ACCOUNT</b></a><?php endif; ?>
			</div>
		</div>
	</div>
	<div class="login-description">
		<div class="accountlogin">Account Login</div>
		<div class="details">
			<?php if(isset($forgotPasswordUrl)): ?>
			<span class="accountlogintitle">Forgot your password?</span><br>
			Click <a href="<?php echo $forgotPasswordUrl; ?>" class="underlinetext">here</a>
			and simply enter your email address. If the email is registered,
			we'll send the password to that email address.
			<?php endif; ?>
			<span class="accountlogintitle">The website isn't accepting my
				password,<br> now what?
			</span><br> The password is case sensitive. Please verify that the
			CAPS LOCK key on your keyboard is not activated.
		</div>
	</div>

</div>
<?php
/* $this->headStyle()->captureStart();
echo $loginForm->getCss();
$this->headStyle()->captureEnd(); */






